name: Check gfall data update workflow

on:
  schedule:
    - cron: '0 0 * * 0'  #runs on every Sunday midnight
  workflow_dispatch:
  
env:
  SOURCE_URL: http://kurucz.harvard.edu/linelists/gfall/gfall.dat.           #URL of the gfall line lists 
  CHANGES_URL: http://kurucz.harvard.edu/linelists/gfall/changesall.tab      #URL of the changes mentioned by Kuruz
  CREATION_URL: http://kurucz.harvard.edu/linelists/gfall/creationdates.dat  #creation date of each data
  README_URL: http://kurucz.harvard.edu/linelists/gfall/00gffix.readme       #readme file at Kuruz website

jobs:
  build:
    runs-on: ubuntu-latest

    steps:   
      - name: Checkout github repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Download data
        id: download_data
        run: |
          mkdir -p linelists/gfall
          wget -q -o "Mozilla/4.0" $SOURCE_URL -O /linelists/gfall/gfall.dat
          wget -q -o "Mozilla/4.0" $CHANGES_URL -O /linelists/gfall/changesall.dat
          wget -q -o "Mozilla/4.0" $CREATION_URL -O /linelists/gfall/creationdates.dat
          wget -q -o "Mozilla/4.0" $README_URL -O /linelists/gfall/readme.dat
          
      - name: Compare changes
        id: compare
        run: |
          git add .
          git diff --quiet --exit-code --cached
          FILE_CHANGE=$?
          echo "change=$FILE_CHANGE" >> "$GITHUB_OUTPUT"

      - name: Commit files to git
        id: commit_changes
        if: ${{ steps.compare.outputs.change == 1 }}
        run: |
          git commit -m "New dataset added"

      - name: Push changes
        if: ${{ steps.compare.outputs.change == 1 }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
